// Lessons listing
const lessonsObj = {
    1: {
        id: 1,
        subject: "Math",
        imgSrc: "assets/math.png",
        imgAlt: "assets/math.png",
        location: 'London',
        price: 12,
        spaces: 7,
    },
    2: {
        id: 2,
        subject: "Biology",
        imgSrc: "assets/Biology.png",
        imgAlt: "assets/Biology.png",
        location: 'London',
        price: 6,
        spaces: 7,
    },
    3: {
        id: 3,
        subject: "Science",
        imgSrc: "assets/Science.png",
        imgAlt: "assets/Science.png",
        location: 'London',
        price: 10,
        spaces: 5,
    },
    4: {
        id: 4,
        subject: "Literacy",
        imgSrc: "assets/Literacy.png",
        imgAlt: "assets/Literacy.png",
        location: 'London',
        price: 3,
        spaces: 18,
    },
    5: {
        id: 5,
        subject: "Sports",
        imgSrc: "assets/Sports.png",
        imgAlt: "assets/Sports.png",
        location: 'Hendon',
        price: 26,
        spaces: 14,
    },
    6: {
        id: 6,
        subject: "Sports",
        imgSrc: "assets/Sports.png",
        imgAlt: "assets/Sports.png",
        location: 'Greenwich',
        price: 27,
        spaces: 10,
    },
    7: {
        id: 7,
        subject: "Driving",
        imgSrc: "assets/Driving.png",
        imgAlt: "assets/Driving.png",
        location: 'London',
        price: 30,
        spaces: 12,
    },
    8: {
        id: 8,
        subject: "English",
        imgSrc: "assets/English.png",
        imgAlt: "assets/English.png",
        location: 'Hendon',
        price: 16,
        spaces: 5,
    },
    9: {
        id: 9,
        subject: "English",
        imgSrc: "assets/English.png",
        imgAlt: "assets/English.png",
        location: 'Green Street',
        price: 19,
        spaces: 10,
    },
    10: {
        id: 10,
        subject: "Driving",
        imgSrc: "assets/Driving.png",
        imgAlt: "assets/Driving.png",
        location: 'Manchester',
        price: 30,
        spaces: 9,
    },
}